### ISSUE TITLE
vue-router历史模式下，在非根页面加载cesium报错。

### ISSUE THREAD

**Issue by duwensi** [isboyjc/vue-cli-plugin-cesium#1]
以下是进行测试的情形：
1. 历史模式:
  - 根页面(比如：http://localhost:8080/)：正常。
  - 非根页面(比如：http://localhost:8080/about)：报错如下图，并且有部分图标图片无法加载。
2. 哈希模式:
  - 所有页面下均正常。
![image](https://user-images.githubusercontent.com/8371027/71863399-b3ef7b00-3137-11ea-9ebd-44538e060c51.png)

**Comment by isboyjc** [comment]
不好意思，我忽略了history模式测试，本周内会解决这个问题

**Comment by duwensi** [comment]
另外还漏了这个配置：
```
new CopyWebpackPlugin([{
    from: path.join(cesiumSource, 'ThirdParty'),
    to: 'ThirdParty'
}])
```

**Comment by isboyjc** [comment]
已更新，抱歉，前段时间有其他事

history模式下并非此插件错误，而是vue-cli配置错误
history模式下本地开发需要在vue.config.js文件下配置publicPath，生产环境需配置nginx
