### ISSUE TITLE
Cannot set property 'defaultAccessToken' of undefined

### ISSUE THREAD

**Issue by SandySY** [isboyjc/vue-cli-plugin-cesium#13]
Cesium.Ion.defaultAccessToken = `my token`;
![image](https://user-images.githubusercontent.com/32258715/103056317-9a10a780-45d7-11eb-8d20-3b173ca7445f.png)

package：
"dependencies": {
    "cesium": "1.20.0",
    "core-js": "^3.6.5",
    "vue": "^2.6.11",
    "vue-cli-plugin-cesium": "^1.1.7",
    "vue-router": "^3.2.0",
    "vuex": "^3.4.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0", ...
}

**Comment by isboyjc** [comment]
你好，您使用的cesium版本较老，请尝试使用新的版本

**Comment by SandySY** [comment]
手动卸载再装"cesium": "^1.76.0"后解决， 迷糊了， 怎么会装了1.20.0的呢， 谢谢老铁
