### ISSUE TITLE
请问1.67以及以后的版本也能适配吗？

### ISSUE THREAD

**Issue by wewindy** [isboyjc/vue-cli-plugin-cesium#2]
如题，谢谢

**Comment by isboyjc** [comment]
目前是安装的1.64版本，最近几天会更新

**Comment by isboyjc** [comment]
已更新，此插件只是用于连接cesium和vue的一个插件，并无cesium版本问题，之前插件版本默认会安装最新版本的cesium，此次更新安装cesium版本可自行选择
