### ISSUE TITLE
Can not work on Win7&nodejs 12

### ISSUE THREAD

**Issue by xiuyangzhe** [isboyjc/vue-cli-plugin-cesium#6]
I find it can't build the Cesium files like 'Assets'、'ThirdParty'... ,I copy the files to the public folder,it's ok.
ps:反正就是win7 nodejs12环境，win7升级不了node14. 运行这些文件404，我拿这些文件复制过去就可以用

**Comment by isboyjc** [comment]
没有明白您表达的意思
