### ISSUE TITLE
老大，报错

### ISSUE THREAD

**Issue by iEricZHENG** [isboyjc/vue-cli-plugin-cesium#8]
1.方式二操作：
`npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path D:\workspace\KingoSpace\vue_cesium\vue-cli-plugin-cesium-demo\node_modules\_accepts@1.3.7@accepts\node_modules\negotiator
npm ERR! dest D:\workspace\KingoSpace\vue_cesium\vue-cli-plugin-cesium-demo\node_modules\_accepts@1.3.7@accepts\node_modules\negotiator
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, rename 'D:\workspace\KingoSpace\vue_cesium\vue-cli-plugin-cesium-demo\node_modules\_accepts@1.3.7@accepts\node_modules\negotiator' -> 'D:\workspace\KingoSpace\vue_cesium\vue-cli-plugin-cesium-demo\node_modules\_accepts@1.3.7@accepts\node_modules\negotiator'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent`

**Comment by isboyjc** [comment]
你好，可以提供下当前环境和项目环境，以及一些报错场景截图吗，不然很难判断😄
